# RE Quantitative Data Analysis

In [1]:
import pandas as pd

df = pd.read_csv("datasets/quantitative_data.csv")
df.head()

,respondent_id,role_group,experience_code,familiarity_code,fr_auth,fr_role_mgmt,fr_student_mgmt,fr_hte_mgmt,fr_internship_mgmt,fr_internship_status_tracking,fr_attendance_mgmt,fr_evaluation_mgmt,fr_document_mgmt,fr_reporting,fr_audit_logging,nfr_security,nfr_reliability,nfr_usability,nfr_compliance,approval
0,R01,faculty,2,4,5,5,5,3,5,5,4,5,5,5,5,5,5,5,5,approved_revision
1,R02,ojt_coordinator,4,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,approved
2,R03,faculty,2,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,approved_revision
3,R04,faculty,2,4,4,5,4,5,5,5,5,5,4,5,5,5,5,5,5,approved
4,R05,faculty,1,3,5,5,5,5,5,5,5,5,5,4,4,5,5,5,5,approved

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   respondent_id                  11 non-null     str
 1   role_group                     11 non-null     str
 2   experience_code                11 non-null     int64
 3   familiarity_code               11 non-null     int64
 4   fr_auth                        11 non-null     int64
 5   fr_role_mgmt                   11 non-null     int64
 6   fr_student_mgmt                11 non-null     int64
 7   fr_hte_mgmt                    11 non-null     int64
 8   fr_internship_mgmt             11 non-null     int64
 9   fr_internship_status_tracking  11 non-null     int64
 10  fr_attendance_mgmt             11 non-null     int64
 11  fr_evaluation_mgmt             11 non-null     int64
 12  fr_document_mgmt               11 non-null     int64
 13  fr_reporting                   11 non-null     int64
 14  fr_audit_logging               11 non-null     int64
 15  nfr_security                   11 non-null     int64
 16  nfr_reliability                11 non-null     int64
 17  nfr_usability                  11 non-null     int64
 18  nfr_compliance                 11 non-null     int64
 19  approval                       11 non-null     str
dtypes: int64(17), str(3)
memory usage: 1.8 KB

In [3]:
df.isnull().sum()

respondent_id                    0
role_group                       0
experience_code                  0
familiarity_code                 0
fr_auth                          0
fr_role_mgmt                     0
fr_student_mgmt                  0
fr_hte_mgmt                      0
fr_internship_mgmt               0
fr_internship_status_tracking    0
fr_attendance_mgmt               0
fr_evaluation_mgmt               0
fr_document_mgmt                 0
fr_reporting                     0
fr_audit_logging                 0
nfr_security                     0
nfr_reliability                  0
nfr_usability                    0
nfr_compliance                   0
approval                         0
dtype: int64

In [4]:
df.describe()

,experience_code,familiarity_code,fr_auth,fr_role_mgmt,fr_student_mgmt,fr_hte_mgmt,fr_internship_mgmt,fr_internship_status_tracking,fr_attendance_mgmt,fr_evaluation_mgmt,fr_document_mgmt,fr_reporting,fr_audit_logging,nfr_security,nfr_reliability,nfr_usability,nfr_compliance
count,11.000000,11.000000,11.000000,11.0,11.000000,11.000000,11.0,11.0,11.000000,11.0,11.000000,11.000000,11.000000,11.0,11.0,11.0,11.000000
mean,2.636364,2.909091,4.818182,5.0,4.818182,4.727273,5.0,5.0,4.818182,5.0,4.818182,4.909091,4.727273,5.0,5.0,5.0,4.909091
std,1.026911,0.700649,0.404520,0.0,0.404520,0.646670,0.0,0.0,0.404520,0.0,0.404520,0.301511,0.467099,0.0,0.0,0.0,0.301511
min,1.000000,2.000000,4.000000,5.0,4.000000,3.000000,5.0,5.0,4.000000,5.0,4.000000,4.000000,4.000000,5.0,5.0,5.0,4.000000
25%,2.000000,2.500000,5.000000,5.0,5.000000,5.000000,5.0,5.0,5.000000,5.0,5.000000,5.000000,4.500000,5.0,5.0,5.0,5.000000
50%,2.000000,3.000000,5.000000,5.0,5.000000,5.000000,5.0,5.0,5.000000,5.0,5.000000,5.000000,5.000000,5.0,5.0,5.0,5.000000
75%,3.500000,3.000000,5.000000,5.0,5.000000,5.000000,5.0,5.0,5.000000,5.0,5.000000,5.000000,5.000000,5.0,5.0,5.0,5.000000
max,4.000000,4.000000,5.000000,5.0,5.000000,5.000000,5.0,5.0,5.000000,5.0,5.000000,5.000000,5.000000,5.0,5.0,5.0,5.000000

In [5]:
# categorical dist.
# Role distribution
df['role_group'].value_counts()

role_group
faculty            7
ojt_coordinator    2
hte_supervisor     2
Name: count, dtype: int64

In [6]:
# categorical dist.
# Approval distribution
df['approval'].value_counts()

approval
approved             6
approved_revision    4
not_approved         1
Name: count, dtype: int64

In [7]:
# categorical dist.
# Experience distribution
df['experience_code'].value_counts().sort_index()

experience_code
1    1
2    5
3    2
4    3
Name: count, dtype: int64

In [8]:
# categorical dist.
# Familiarity distribution
df['familiarity_code'].value_counts().sort_index()

familiarity_code
2    3
3    6
4    2
Name: count, dtype: int64

In [9]:
# Functional Requirement Analysis
# Compute mean scores o determine highest/lowest rated requirements
fr_cols = [
    'fr_auth',
    'fr_role_mgmt',
    'fr_student_mgmt',
    'fr_hte_mgmt',
    'fr_internship_mgmt',
    'fr_internship_status_tracking',
    'fr_attendance_mgmt',
    'fr_evaluation_mgmt',
    'fr_document_mgmt',
    'fr_reporting',
    'fr_audit_logging'
]

fr_means = df[fr_cols].mean().sort_values(ascending=False)
print(fr_means)

fr_role_mgmt                     5.000000
fr_internship_status_tracking    5.000000
fr_internship_mgmt               5.000000
fr_evaluation_mgmt               5.000000
fr_reporting                     4.909091
fr_student_mgmt                  4.818182
fr_auth                          4.818182
fr_document_mgmt                 4.818182
fr_attendance_mgmt               4.818182
fr_hte_mgmt                      4.727273
fr_audit_logging                 4.727273
dtype: float64

In [10]:
# Non-functional Requirement Analysis
nfr_cols = [
    'nfr_security',
    'nfr_reliability',
    'nfr_usability',
    'nfr_compliance'
]

nfr_means = df[nfr_cols].mean().sort_values(ascending=False)
print(nfr_means)

nfr_security       5.000000
nfr_reliability    5.000000
nfr_usability      5.000000
nfr_compliance     4.909091
dtype: float64

In [11]:
# Overall Requirement Validity
# Compute overall average score or the Overall weighted mean
all_req_cols = fr_cols + nfr_cols
overall_mean = df[all_req_cols].mean().mean()
print(overall_mean)

4.903030303030303

In [12]:
# Approval Analysis
df['approval'].value_counts()
approval_pct = df['approval'].value_counts(normalize=True) * 100
print(approval_pct)

approval
approved             54.545455
approved_revision    36.363636
not_approved          9.090909
Name: proportion, dtype: float64

In [13]:
# Combined approval as a key meric
accepted = df['approval'].isin(['approved', 'approved_revision']).sum()
total = len(df)

print((accepted / total) * 100)

90.9090909090909

In [14]:
# Group Analysis (compare by role)
# Ex: Do faculty rate differently from coordinators?
df.groupby('role_group')[fr_cols + nfr_cols].mean()

,fr_auth,fr_role_mgmt,fr_student_mgmt,fr_hte_mgmt,fr_internship_mgmt,fr_internship_status_tracking,fr_attendance_mgmt,fr_evaluation_mgmt,fr_document_mgmt,fr_reporting,fr_audit_logging,nfr_security,nfr_reliability,nfr_usability,nfr_compliance
role_group,,,,,,,,,,,,,,,
faculty,4.714286,5.0,4.857143,4.571429,5.0,5.0,4.714286,5.0,4.857143,4.857143,4.857143,5.0,5.0,5.0,5.0
hte_supervisor,5.000000,5.0,4.500000,5.000000,5.0,5.0,5.000000,5.0,4.500000,5.000000,4.500000,5.0,5.0,5.0,4.5
ojt_coordinator,5.000000,5.0,5.000000,5.000000,5.0,5.0,5.000000,5.0,5.000000,5.000000,4.500000,5.0,5.0,5.0,5.0